= Java开发问题排查方法与技巧

== 通用方法

=== 日志

不论是开发或者使用其它组件，一定要知道它的日志保存在哪

配置文件配置日志位置

systemctl

=== 搜索

关键字选择

Google  >>   Bing    >>  baidu

官方文档、项目Issue、javadoc


例如搜索发现项目加入spring security后CPU利用率升高


=== 重现

本地环境重现

快速重现，甚至为了重现问题单独开发一个程序

重现一般也是和下一节的缩小范围一起反复尝试


=== 缩小范围

删除不相关代码

新建测试项目
单独开发一个程序还可以避免受其它功能影响，例如axis2和cxf会相互影响

=== 替换
有时候实现同一目的的方法有很多种，例如nginx、haproxy、端口映射都能实现反向代理，与其花大量时间解决一个方案存在的问题不如直接选择另一个方案


=== Debug & Remote Debug

==== tomcat远程调试


==== spring boot远程调试


== 问题分类

=== 系统资源


==== CPU占用高




==== 内存溢出
内存溢出有多种报错形式
jstat
HeapDumpOnOutOfMemory
MAT


=== 接口

curl

webservice(优先选择生成客户端代码)

浏览器控制台copy as curl

部署到服务器后接口访问不到(防火墙问题)

接口调用卡死(jstack查看线程栈信息，查看gc确认是否存在内存溢出问题)

=== 采集
回显取不到或取不全

回车问题

=== SpringMVC

接口写了，访问404
项目部署上去

=== Spring Boot
自动配置

=== Spring Security

UsernamePasswordFilter


=== Spring Data JPA


=== Maven



==== 依赖冲突




==== 传递依赖失败



=== Tomcat
出错了 catalina.out 没异常 +
日志刷太快 打印不好看
日志分隔

=== MySQL



=== Elasticsearch



=== Kafka



=== 其它
前后端责任不清晰，相互推诿

== 总结

以上都是简单问题
夯实基础知识

:sectnums!:
== Appendices

bilibili::BV1vt411g7F5[]