= Interview-Questions



== Code

1. 如何实现多继承(不是真正的多继承，指一个类包含两个其它类的功能)
2. equals()方法需要具备自反性、对称性、传递性、一致性，分别写几个违背对称性、传递性、一致性的示例代码
3. 说出3到5个常见的运行时异常
4. 说出5个以上Object类中的方法
5. 微服务单点登录实现原理
6. MyBatis注入与执行原理
7。记住我功能实现过程
8. jdk8之后新特性
9. 线程池关键参数及其意义
10. fixedPoll singlePool cachedPool 使用的队列
11. 设计模式
12. 内存溢出时被占用的内存会被回收吗
13. 内存溢出时线程会终止吗
14. 内存溢出问题如何排查
15. 常用单元测试框架与单元测试注意事项
16. 页面卡住问题排查方法与思路
17. 云原生
18. 数据权限实现思路
19. Spring Security框架原理(用过的话)
20. OAuth2
21. 什么是系统调用、物理内存与虚拟内存
22. @Scheduled实现原理
23. websocket连接过程
24. SpringMVC请求处理过程
25. spring-jdbc事务使用方式
26. jdk中日期相关的类以及塔曼的区别
27. 请求参数校验与Bean Validation
28. 用户登录功能的实现过程
29. SpringMVC的拦截器以及它的使用场景
30. 常用的日志框架以及它们之间的关系
31. CORS是什么
32. GET与POST的区别
33. Java中有哪些函数式接口
34. http缓存机制与缓存相关的响应头
35. SpringMVC用的哪个库实现Json序列号与反序列号，Jackson与Fastjson的比较
36. http2新特性，Spring Boot支持使用http2吗
37. Spring Boot常用的有哪些starter，分别用来做什么
38. jdk中常用的排查问题工具
39. Spring Boot Actuator的作用
40. Maven同一个依赖多个版本怎么选择
41. Spring Boot应用怎么修改日志级别
42. Spring Boot默认用的什么日志框架
43. Spring Boot怎么做国际化
44. Spring Boot应用怎么打包成容器镜像
45. Linux上用什么命令把文件中一个词替换成另一个词
46. 怎么监控Spring Boot应用
47. k8s中怎么暴露服务
48. k8s中StorageClass是什么



== ThreadLocal
1. 使用WeakReference是因为ThreadLocal可能在线程结束之前就已经使用完了，如果不用弱引用，线程结束前ThreadLocal都不能被回收，这里与方法局部变量区别在于方法执行完成后其局部变量就能被回收，而ThreadLocal是Thread的属性，不用弱引用的话就只能等线程结束后再被回收；另一方面ThreadLocal是在多个线程中使用的，如果是强引用只要存在一个线程没结束ThreadLocal就不能被回收。
2. 内存泄漏问题与弱引用无关，指的是在tomcat这类连接池的场景，线程根本不会结束，例如在springMVC的controller中声明一个ThreadLocal用于保存特定请求参数，请求结束后由于线程并未结束，之前保存的参数也仍然在内存中。
3. 另一种内存泄漏的场景就是ThreadLocal已经被回收了但线程还没结束，其中的Entry也已经失效了但还不能被回收，由于Value不能回收，它的ClassLoader也不能被回收，因此可能同时会导致ClassLoader内存泄漏。

 If a short-lived object is held for a long time by a long-lived object, it will cause the short-lived object to not be released after use, resulting in memory leaks.

 https://stackoverflow.com/questions/17968803/threadlocal-memory-leak
 https://www.programmersought.com/article/88854924004/
 https://java.jiderhamn.se/2012/01/29/classloader-leaks-iv-threadlocal-dangers-and-why-threadglobal-may-have-been-a-more-appropriate-name/
